<a href="https://colab.research.google.com/github/Atharv26j13/2/blob/main/data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
data_type = [('name','S90'),('class',int),('height',float)]
students_details = [('Hammer',5,100.0),('Nail',6,52.5 ),('Screw',1,4.6),('Military Grade Titanium Chainsaw',99,1562.8)]

students = np.array(students_details,dtype=data_type)
print('Original array:')
print(students)
print('Sort by height')
print(np.sort(students,order='height'))

Original array:
[(b'Hammer',  5,  100. ) (b'Nail',  6,   52.5) (b'Screw',  1,    4.6)
 (b'Military Grade Titanium Chainsaw', 99, 1562.8)]
Sort by height
[(b'Screw',  1,    4.6) (b'Nail',  6,   52.5) (b'Hammer',  5,  100. )
 (b'Military Grade Titanium Chainsaw', 99, 1562.8)]


In [10]:
import numpy as np

# Create a 3x3 array of floats from 0 to 8
a = np.arange(9, dtype=np.float64).reshape(3, 3)
print("First Array:")
print(a)
print("\n")

# Create a column vector (3x1) so operations happen column-wise
b = np.array([[10], [10], [10]])
print("Second Array (Column Vector):")
print(b)
print("\n")

# Perform element-wise operations
print("Add the two arrays:")
print(np.add(a, b))
print("\n")

print("Subtract the two arrays:")
print(np.subtract(a, b))
print("\n")

print("Multiply the two arrays:")
print(np.multiply(a, b))
print("\n")

print("Divide the two arrays:")
print(np.divide(a, b))
print("\n")



First Array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second Array (Column Vector):
[[10]
 [10]
 [10]]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


